name: Docker Build and Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [api-gateway, menu-services, order-services, payment-services, inventory-services, customer-services]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ hmik }}
          password: ${{ 786103 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Cafe_Management_System/${{ matrix.service }}
          push: true
          tags: ${{ hmik }}/${{ matrix.service }}:latest
