version: '3.9'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service

  menu-service:
    build: ./menu-services
    ports:
      - "3001:3000"

  order-service:
    build: ./order-services
    ports:
      - "3002:3000"

  payment-service:
    build: ./payment-services
    ports:
      - "3003:3000"

  inventory-service:
    build: ./inventory-services
    ports:
      - "3004:3000"

  customer-service:
    build: ./customer-services
    ports:
      - "3005:3000"
